Fix aesgcm not accounting for padding
mozilla/rust-ece pull request #45
Opened 2020-09-02 21:43 UTC by Jordandev678

If I'm correct Firefox Fenix uses application-services which uses this library for push notification decryption of aesgcm. I'm running into it not accounting for padding correctly. If I understand the spec correctly the first two bytes are the number of following padding bytes then the message. The current code only skips the first two bytes but doesn't then use that information to skip ahead and remove the padding.

Related Fenix bug https://github.com/mozilla-mobile/fenix/issues/14582 

This updates the unpad function in aesgcm to use those bytes to skip the padding and adds an accompanying unit test.

First piece of rust code so review carefully :)

2020-09-03 14:53 UTC, jrconlin approved these changes
approved albeit with considerations.

2020-09-03 14:53 UTC, jrconlin commented
As noted in my comment on [https://github.com/mozilla-mobile/fenix/issues/14582](https://github.com/mozilla-mobile/fenix/issues/14582#issuecomment-686542269), if this is an issue that only impacts `aesgcm`, I'm tempted to suggest that it not be fixed in order to further encourage folk to use the correct `aes128gcm` content encoding.

2020-09-03 15:20 UTC, Jordandev678 commented
I totally get the point, but to add to the comment I just left in the fenix issue. Other providers aside for a moment on a personal note I just tried to set our system to aes128gsm and it's not supported. For various reasons I'm currently locked into the current library version. Updating is a work in progress that will be finalized before the new year but in the mean time I'm unfortunately stuck. If I can't get this fixed the outcome won't be us updating sooner it'll be us dropping Firefox from support and just rolling with chrome. I'd really prefer to not have to do that given the choice if for no other reason than FF is my own default browser 🙂

2020-09-08 04:38 UTC, rfk requested changes
Thanks!

IIUC, the [spec](https://tools.ietf.org/html/draft-ietf-httpbis-encryption-encoding-03#section-2) also says that "A receiver MUST fail to decrypt if any padding octet other than the first two are non-zero". Would you mind adding an additional check for that case as well? (Just in case it's guarding against some cryptographic edge-case that we don't know about).

I think something like `block[2..(2 + padding_size)].any(|b| b != 0u8)` would be the appropriate condition to check, although I haven't tried it.

2020-09-09 11:55 UTC, Jordandev678 commented
Close, just had to grab the iterator first. Update pushed.

2020-09-10 03:49 UTC, rfk approved these changes
Thank you!

2020-09-10 03:49 UTC, merged